CREATE CACHED TABLE NEXD_SEQUENCE (
       NAME VARCHAR(255) NOT NULL
     , ID INTEGER NOT NULL
     , PRIMARY KEY (NAME)
);

CREATE CACHED TABLE NEXD_COLLECTION (
       ID INTEGER NOT NULL
     , PID INTEGER
     , TYPE SMALLINT NOT NULL
     , NAME VARCHAR(255)
     , PRIMARY KEY (ID)
);
CREATE INDEX SYS_IDX_1 ON NEXD_COLLECTION (PID);

CREATE CACHED TABLE NEXD_RESOURCE (
       ID INTEGER NOT NULL
     , CID INTEGER NOT NULL
     , TYPE SMALLINT NOT NULL
     , NAME VARCHAR(255) NOT NULL
     , PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_CT_4_7 ON NEXD_RESOURCE (CID, NAME);
CREATE INDEX MY_RESOURCE_IDX ON NEXD_RESOURCE (ID);
CREATE INDEX SYS_IDX_5 ON NEXD_RESOURCE (CID);

CREATE TABLE NEXD_DOM_NODE (
       ID INTEGER NOT NULL
     , LFT INTEGER NOT NULL
     , RGT INTEGER NOT NULL
     , TYPE SMALLINT NOT NULL
     , RID INTEGER NOT NULL
     , PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_CT_34_36 ON NEXD_DOM_NODE (ID, LFT, RGT);
CREATE INDEX MY_NODE_IDX ON NEXD_DOM_NODE (ID, RID);
CREATE INDEX MY_NODE_LFT_RGT_RID_IDX ON NEXD_DOM_NODE (LFT, RGT, RID);
CREATE INDEX SYS_IDX_37 ON NEXD_DOM_NODE (RID);

CREATE CACHED TABLE NEXD_DOM_ATTR (
       NID INTEGER NOT NULL
     , NAME VARCHAR(255) NOT NULL
     , VALUE VARCHAR(2147483647)
     , PRIMARY KEY (NID)
);
CREATE INDEX MY_ATTR_IDX ON NEXD_DOM_ATTR (NID);
CREATE INDEX SYS_IDX_46 ON NEXD_DOM_ATTR (NID);

CREATE CACHED TABLE NEXD_DOM_DOCTYPE (
       NID INTEGER NOT NULL
     , NAME VARCHAR(255) NOT NULL
     , PUBLICID VARCHAR(2147483647)
     , SYSTEMID VARCHAR(2147483647)
     , SUBSET VARCHAR(2147483647)
     , PRIMARY KEY (NID)
);
CREATE INDEX MY_DTD_IDX ON NEXD_DOM_DOCTYPE (NID);
CREATE INDEX SYS_IDX_62 ON NEXD_DOM_DOCTYPE (NID);

CREATE CACHED TABLE NEXD_DOM_DOCUMENT (
       NID INTEGER NOT NULL
     , VERSION VARCHAR(4) NOT NULL
     , ENCODING VARCHAR(20)
     , STANDALONE BIT
     , PRIMARY KEY (NID)
);
CREATE INDEX MY_DOC_IDX ON NEXD_DOM_DOCUMENT (NID);
CREATE INDEX SYS_IDX_40 ON NEXD_DOM_DOCUMENT (NID);

CREATE CACHED TABLE NEXD_DOM_ELEMENT (
       NID INTEGER NOT NULL
     , NAME VARCHAR(255) NOT NULL
     , PRIMARY KEY (NID)
);
CREATE INDEX MY_ELEM_IDX ON NEXD_DOM_ELEMENT (NID);
CREATE INDEX SYS_IDX_43 ON NEXD_DOM_ELEMENT (NID);

CREATE CACHED TABLE NEXD_DOM_ENTITYREF (
       NID INTEGER NOT NULL
     , NAME VARCHAR(255) NOT NULL
     , PRIMARY KEY (NID)
);
CREATE INDEX MY_ENTITY_IDX ON NEXD_DOM_ENTITYREF (NID);
CREATE INDEX SYS_IDX_55 ON NEXD_DOM_ENTITYREF (NID);

CREATE CACHED TABLE NEXD_DOM_PI (
       NID INTEGER NOT NULL
     , TARGET VARCHAR(255) NOT NULL
     , DATA VARCHAR(2147483647)
     , PRIMARY KEY (NID)
);
CREATE INDEX MY_PI_IDX ON NEXD_DOM_PI (NID);
CREATE INDEX SYS_IDX_52 ON NEXD_DOM_PI (NID);

CREATE CACHED TABLE NEXD_DOM_TEXT (
       NID INTEGER NOT NULL
     , VALUE VARCHAR(2147483647)
     , PRIMARY KEY (NID)
);
CREATE INDEX MY_TEXT_IDX ON NEXD_DOM_TEXT (NID);
CREATE INDEX SYS_IDX_49 ON NEXD_DOM_TEXT (NID);

CREATE CACHED TABLE NEXD_SCHEMA (
       CID INTEGER NOT NULL
     , TYPE TINYINT NOT NULL
     , SCHEMA VARCHAR(2147483647) NOT NULL
     , PRIMARY KEY (CID)
);
CREATE INDEX SYS_IDX_59 ON NEXD_SCHEMA (CID);

CREATE CACHED TABLE NEXD_COLLECTION_VCOLLECTION (
       CID INTEGER NOT NULL
     , VCID INTEGER NOT NULL
     , PATH VARCHAR(2147483647) NOT NULL
     , PRIMARY KEY (CID, VCID)
);
CREATE INDEX SYS_IDX_72 ON NEXD_COLLECTION_VCOLLECTION (CID);
CREATE INDEX SYS_IDX_74 ON NEXD_COLLECTION_VCOLLECTION (VCID);

ALTER TABLE NEXD_COLLECTION
  ADD CONSTRAINT PARENTID
      FOREIGN KEY (PID)
      REFERENCES NEXD_COLLECTION (ID)
   ON DELETE CASCADE;

ALTER TABLE NEXD_RESOURCE
  ADD CONSTRAINT SYS_FK_3
      FOREIGN KEY (CID)
      REFERENCES NEXD_COLLECTION (ID)
   ON DELETE CASCADE;

ALTER TABLE NEXD_DOM_NODE
  ADD CONSTRAINT SYS_FK_35
      FOREIGN KEY (RID)
      REFERENCES NEXD_RESOURCE (ID)
   ON DELETE CASCADE;

ALTER TABLE NEXD_DOM_ATTR
  ADD CONSTRAINT SYS_FK_45
      FOREIGN KEY (NID)
      REFERENCES NEXD_DOM_NODE (ID)
   ON DELETE CASCADE;

ALTER TABLE NEXD_DOM_DOCTYPE
  ADD CONSTRAINT SYS_FK_61
      FOREIGN KEY (NID)
      REFERENCES NEXD_DOM_NODE (ID)
   ON DELETE CASCADE;

ALTER TABLE NEXD_DOM_DOCUMENT
  ADD CONSTRAINT SYS_FK_39
      FOREIGN KEY (NID)
      REFERENCES NEXD_DOM_NODE (ID)
   ON DELETE CASCADE;

ALTER TABLE NEXD_DOM_ELEMENT
  ADD CONSTRAINT SYS_FK_42
      FOREIGN KEY (NID)
      REFERENCES NEXD_DOM_NODE (ID)
   ON DELETE CASCADE;

ALTER TABLE NEXD_DOM_ENTITYREF
  ADD CONSTRAINT SYS_FK_54
      FOREIGN KEY (NID)
      REFERENCES NEXD_DOM_NODE (ID)
   ON DELETE CASCADE;

ALTER TABLE NEXD_DOM_PI
  ADD CONSTRAINT SYS_FK_51
      FOREIGN KEY (NID)
      REFERENCES NEXD_DOM_NODE (ID)
   ON DELETE CASCADE;

ALTER TABLE NEXD_DOM_TEXT
  ADD CONSTRAINT SYS_FK_48
      FOREIGN KEY (NID)
      REFERENCES NEXD_DOM_NODE (ID)
   ON DELETE CASCADE;

ALTER TABLE NEXD_SCHEMA
  ADD CONSTRAINT SYS_FK_58
      FOREIGN KEY (CID)
      REFERENCES NEXD_COLLECTION (ID)
   ON DELETE CASCADE;

ALTER TABLE NEXD_COLLECTION_VCOLLECTION
  ADD CONSTRAINT SYS_FK_70
      FOREIGN KEY (CID)
      REFERENCES NEXD_COLLECTION (ID);

ALTER TABLE NEXD_COLLECTION_VCOLLECTION
  ADD CONSTRAINT SYS_FK_71
      FOREIGN KEY (VCID)
      REFERENCES NEXD_COLLECTION (ID)
   ON DELETE CASCADE;

INSERT INTO NEXD_COLLECTION
  (ID, PID, TYPE, NAME)
VALUES
  (1, NULL, 0, 'db');

  
INSERT INTO NEXD_SEQUENCE
  (NAME, ID)
VALUES
  ('nexd_collection', 1);
  
INSERT INTO NEXD_SEQUENCE
  (NAME, ID)
VALUES
  ('nexd_dom_node', 0);
  
INSERT INTO NEXD_SEQUENCE
  (NAME, ID)
VALUES
  ('nexd_resource', 0);