/*
 * Project: nexd 
 * Copyright (C) 2004  Manuel Pichler <manuel.pichler@xplib.de>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
package de.xplib.nexd.xml.dom;

import org.w3c.dom.DOMException;
import org.w3c.dom.Entity;
import org.w3c.dom.Node;

/**
 *  
 * @author Manuel Pichler <manuel.pichler@xplib.de>
 * @version $Rev$
 */
public class EntityImpl extends AbstractParentNode implements Entity {

    /**
     * Constructor ..
     * 
     * @param ownerIn ..
     * @param nodeNameIn ..
     */
    protected EntityImpl(final DocumentImpl ownerIn, final String nodeNameIn) {
        super(ownerIn, nodeNameIn, Node.ENTITY_NODE);
    }

    /**
     * The public identifier associated with the entity if specified, and 
     * <code>null</code> otherwise.
     * 
     * @return ..
     * @see org.w3c.dom.Entity#getPublicId()
     */
    public String getPublicId() {
        // TODO Auto-generated method stub
        return null;
    }

    /**
     * The system identifier associated with the entity if specified, and 
     * <code>null</code> otherwise. This may be an absolute URI or not.
     * 
     * @return ..
     * @see org.w3c.dom.Entity#getSystemId()
     */
    public String getSystemId() {
        // TODO Auto-generated method stub
        return null;
    }

    /**
     * For unparsed entities, the name of the notation for the entity. For 
     * parsed entities, this is <code>null</code>.
     * 
     * @return ..
     * @see org.w3c.dom.Entity#getNotationName()
     */
    public String getNotationName() {
        // TODO Auto-generated method stub
        return null;
    }

    /**
     * An attribute specifying the encoding used for this entity at the time 
     * of parsing, when it is an external parsed entity. This is 
     * <code>null</code> if it an entity from the internal subset or if it 
     * is not known.
     * 
     * @return ..
     * @since DOM Level 3
     * @see org.w3c.dom.Entity#getInputEncoding()
     */
    public String getInputEncoding() {
        // TODO Auto-generated method stub
        return null;
    }

    /**
     * An attribute specifying, as part of the text declaration, the encoding 
     * of this entity, when it is an external parsed entity. This is 
     * <code>null</code> otherwise.
     * 
     * @return ..
     * @since DOM Level 3
     * @see org.w3c.dom.Entity#getXmlEncoding()
     */
    public String getXmlEncoding() {
        // TODO Auto-generated method stub
        return null;
    }

    /**
     * An attribute specifying, as part of the text declaration, the version 
     * number of this entity, when it is an external parsed entity. This is 
     * <code>null</code> otherwise.
     * 
     * @return ..
     * @since DOM Level 3
     * @see org.w3c.dom.Entity#getXmlVersion()
     */
    public String getXmlVersion() {
        // TODO Auto-generated method stub
        return null;
    }

    /**
     * Returns a duplicate of this node, i.e., serves as a generic copy 
     * constructor for nodes. The duplicate node has no parent; (
     * <code>parentNode</code> is <code>null</code>.) and no user data. User 
     * data associated to the imported node is not carried over. However, if 
     * any <code>UserDataHandlers</code> has been specified along with the 
     * associated data these handlers will be called with the appropriate 
     * parameters before this method returns.
     * <br>Cloning an <code>Element</code> copies all attributes and their 
     * values, including those generated by the XML processor to represent 
     * defaulted attributes, but this method does not copy any children it 
     * contains unless it is a deep clone. This includes text contained in 
     * an the <code>Element</code> since the text is contained in a child 
     * <code>Text</code> node. Cloning an <code>Attribute</code> directly, 
     * as opposed to be cloned as part of an <code>Element</code> cloning 
     * operation, returns a specified attribute (<code>specified</code> is 
     * <code>true</code>). Cloning an <code>Attribute</code> always clones 
     * its children, since they represent its value, no matter whether this 
     * is a deep clone or not. Cloning an <code>EntityReference</code> 
     * automatically constructs its subtree if a corresponding 
     * <code>Entity</code> is available, no matter whether this is a deep 
     * clone or not. Cloning any other type of node simply returns a copy of 
     * this node.
     * <br>Note that cloning an immutable subtree results in a mutable copy, 
     * but the children of an <code>EntityReference</code> clone are readonly
     * . In addition, clones of unspecified <code>Attr</code> nodes are 
     * specified. And, cloning <code>Document</code>, 
     * <code>DocumentType</code>, <code>Entity</code>, and 
     * <code>Notation</code> nodes is implementation dependent.
     * 
     * @param deep If <code>true</code>, recursively clone the subtree under 
     *   the specified node; if <code>false</code>, clone only the node 
     *   itself (and its attributes, if it is an <code>Element</code>).
     * @return The duplicate node.
     * @see org.w3c.dom.Node#cloneNode(boolean)
     */
    public Node cloneNode(final boolean deep) {
        // TODO Auto-generated method stub
        return null;
    }
    
    /**
     * <Some description here>
     * 
     * @param nodeIn
     * @return
     * @throws DOMException
     * @see de.xplib.nexd.xml.dom.AbstractParentNode#acceptNode(
     * 		org.w3c.dom.Node)
     */
    protected int acceptNode(final Node nodeIn) throws DOMException {
        // TODO Auto-generated method stub
        return 0;
    }

}
